title: Dotfiles
author:
  name: Matteo Salonia
  email: matteo@salonia.it

description: Matteo Salonia's dotfiles

remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme

minima:
  skin: auto

social_links:
  - { platform: github,         user_url: "https://github.com/saloniamatteo/dotfiles" }
