#!/bin/bash
# Warn the user if the battery capacity is low
# Run this script with cron (see "man crontab")

# Make a beep sound at 1000Hz for 0.25sec
function makebeep() {
	speaker-test -t sine -f 1000 >/dev/null 2>&1 & pid=$!; sleep 0.25s; kill -9 $pid
}

# Get a list of batteries
for battery in /sys/class/power_supply/BAT?*; do
	# Get battery capacity
	capacity=$(cat "$battery"/capacity)

	# Transform a number like "9" to "09", because bash fails if
	# there is a statement checking if 9 < 10, but works if 09 < 10
	[[ $capacity =~ ^[0-9]$ ]] && capacity="0${capacity}"

	# Avoid sending unnecessary notifications
	[[ $capacity > 20 ]] && exit 0

	# Get the current battery status (charging/discharging)
	status=$(cat "$battery"/status)

	# Avoid sending unnecessary notifications
	[[ $status = "Charging" ]] && exit 0

	# Get the name of the battery (BATx)
	batteryname=$(echo $battery | grep -Eo "BAT[0-9]")

	# Check battery status
	if [[ $status = "Unknown" || $status = "Discharging" ]]; then
		# Make beep sound
		makebeep

		# Display notification for $time ms based on charge
		if [ $capacity -le 10 ]; then
			time=10000
		else
			time=6500
		fi

		# Send notification
		/usr/bin/notify-send -u critical -t $time "[$batteryname] Battery charge low" "Please charge battery $batteryname ($capacity%)."
	fi
done
