#!/bin/sh

[ $(whoami) = "root" ] && root="" || root="doas"

# increase cpu performance
printf "Increasing CPU performance! \n\n"
# set fan speed to max
echo "level disengaged" | $root tee /proc/acpi/ibm/fan
# apply undervolt
$root rc-service intel-undervolt-loop start
$root intel-undervolt apply
# increase frequency
$root cpupower -c all set -b 0
$root cpupower frequency-set --governor performance
# reserve huge pages
$root sysctl -w vm.nr_hugepages=1280
$root sysctl -w vm.dirty_ratio=40
$root sysctl -w vm.dirty_background_ratio=10
$root sysctl -w vm.swappiness=10
