#!/bin/bash
# Download media (videos, songs) using youtube-dl
# Usage: ./save-media $URL_TO_DOWNLOAD
# Can be used as termux-url-opener for Termux

# Check if we have a url
if [ -z $1 ]; then
	echo "Usage: $0 <url>"
	exit 1
fi

url="$1"
ytdl_cmd="yt-dlp"
save_loc="~/Downloads/youtube-dl"

# Check if directory exists, if not create it
[ ! -d "$save_loc" ] && mkdir "$save_loc"


dl_song() {
	$ytdl_cmd --sponsorblock-remove all -x --embed-thumbnail --audio-format mp3 --audio-quality 0 -c -i "$url" -o "$save_loc/%(title)s.%(ext)s" 
}

dl_video() {
	$ytdl_cmd --sponsorblock-remove all --audio-quality 0 -f "bestvideo[ext=mp4]+bestaudio/best[ext=mp4]" --merge-output-format mp4 -c -i "$url" --audio-quality 0 -f mp4 -o "$save_loc/%(title)s.%(ext)s"
}

# show a list of options
echo "Choose an option:"
echo "1) Download and save as mp3"
echo "2) Download and save as mp4"
printf "> "
read answer

case $answer in
	# download as song/mp3
	1) dl_song ;;

	# download as video/mp4
	2) dl_video ;;

	# download as song/mp3
	*) echo "Input not understood, defaulting to 1..."; dl_song ;;
esac
